version: '3.x'

services:
  auth-headers:
    profiles: ["phase1"]
    image: sakanbeer88/find-stay-place-auth-headers:latest
    volumes:
      - ./.env:/app/.env
    ports:
      - "4000:4000"
    command: >
      sh -c "gunicorn --bind 0.0.0.0:4000 app:app"
    environment:
      - PYTHONPATH=/app
      - USER_AGENT=
    healthcheck:
      test: ["CMD", "python", "-c", "import os; exit(0 if os.path.exists('/app/.env') else 1)"]
      interval: 10s
      timeout: 5s
      retries: 3
      start_period: 5s

  backend:
    profiles: ["phase2"]
    image: sakanbeer88/find-stay-place-backend:latest
    ports:
      - "8000:8000"
    env_file:
      - ./.env
    command: > 
      sh -c "
             python manage.py migrate &&
             gunicorn --bind 0.0.0.0:8000 django_project.wsgi:application"

  frontend:
    profiles: ["phase2"]
    image: sakanbeer88/find-stay-place-frontend:latest
    ports:
      - "5000:80"
    depends_on:
      backend:
        condition: service_started