version: '3.8'

services:
  backend:
    image: sakanbeer88/find-stay-place-backend:latest
    ports:
      - "8000:8000"
    networks:
      - app-network
    environment:
      - USER_AGENT=your_user_agent

  frontend:
    image: sakanbeer88/find-stay-place-frontend:latest
    ports:
      - "5000:80"
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
