services:
  saku-yado:
    profiles:
      - pull
    image: sakanbeer88/saku-yado:latest
    container_name: saku-yado
    ports:
      - "3000:3000"
    volumes:
      - saku-yado:/app

  saku-yado-build:
    profiles:
      - build
    build:
      context: .
      dockerfile: Dockerfile
    image: sakanbeer88/saku-yado:latest
    container_name: saku-yado
    ports:
      - "3000:3000"
    volumes:
      - saku-yado-data:/app

volumes:
  saku-yado-data:
