version: '3.8'

services:
  backend:
    image: sakanbeer88/best-hotel-web-app-backend:latest
    ports:
      - "8000:8000"
    depends_on:
      - frontend

  frontend:
    image: sakanbeer88/best-hotel-web-app-frontend:latest
    ports:
      - "3000:3000"
