services:
  hotel-value-analyzer:
    build:
      context: .
      dockerfile: Dockerfile
    image: hotel-value-analyzer
    container_name: hotel-value-analyzer
    ports:
      - "3000:3000"
    volumes:
      - hotel-value-analyzer-data:/app

volumes:
  hotel-value-analyzer-data:
