version: '3.x'

services:
  backend:
    image: sakanbeer88/find-stay-place-backend:latest
    ports:
      - "8000:8000"
    environment:
      - USER_AGENT=your_user_agent
    user: "1000:1000"

  frontend:
    image: sakanbeer88/find-stay-place-frontend:latest
    ports:
      - "5000:80"
    user: "1001:1001"
