# Generated by Django 5.1.1 on 2024-12-27 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='roomprice',
            name='accommodation_name',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='roomprice',
            name='hotel',
            field=models.CharField(max_length=200),
        ),
    ]
