name: Binary Tests

on:
  push:
    paths:
      - 'web-app-exe/**'
    branches: [ main ]
  pull_request:
    paths:
      - 'web-app-exe/**'
    branches: [ main ]

jobs:
  test-binaries:
    name: Test Binaries
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [windows-latest, macos-latest]
        include:
          - os: windows-latest
            binary: find-place-web-app_windows_amd64.exe
          - os: macos-latest
            binary: find-place-web-app_darwin_amd64

    steps:
    - uses: actions/checkout@v4

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.21'

    - name: Install dependencies
      working-directory: ./web-app-exe
      run: go mod download

    - name: Setup Docker (Windows)
      if: matrix.os == 'windows-latest'
      uses: docker/setup-buildx-action@v3
      with:
        install: true

    - name: Install Docker Desktop (Windows)
      if: matrix.os == 'windows-latest'
      run: |
        choco install docker-desktop -y
        Start-Process "C:\Program Files\Docker\Docker\Docker Desktop.exe"
        # Wait for Docker Desktop to start
        Start-Sleep -s 60
        # Verify Docker is running
        docker version
        # Verify Docker Compose V2
        docker compose version

    - name: Install Docker (macOS)
      if: matrix.os == 'macos-latest'
      run: |
        brew install docker docker-compose
        brew install --cask docker
        # Start Docker Desktop
        open -a Docker
        # Wait for Docker to start
        sleep 60
        # Verify Docker is running
        docker version
        docker compose version

    - name: Install Playwright Browser Dependencies (macOS)
      if: matrix.os == 'macos-latest'
      run: |
        brew install webkit2png
        brew install --cask chromium
        brew install --cask firefox

    - name: Install Playwright Browser Dependencies (Windows)
      if: matrix.os == 'windows-latest'
      run: |
        choco install chromium -y
        choco install firefox -y

    - name: Run Go tests
      working-directory: ./web-app-exe
      run: go test -v ./tests/...

    - name: Build binaries
      working-directory: ./web-app-exe
      run: |
        chmod +x build-exe.sh
        ./build-exe.sh
      shell: bash

    - name: Test binary execution (Windows)
      if: matrix.os == 'windows-latest'
      working-directory: ./web-app-exe
      run: |
        # Test if binary exists
        if (!(Test-Path "${{ matrix.binary }}")) {
          Write-Error "Binary not found"
          exit 1
        }
        # Test if binary is executable
        $env:PATH = "$env:PATH;C:\Program Files\Docker\Docker"
        $process = Start-Process -FilePath ".\${{ matrix.binary }}" -ArgumentList "--help" -NoNewWindow -PassThru -Wait
        if ($process.ExitCode -ne 0) {
          Write-Error "Binary execution failed"
          exit 1
        }

    - name: Test binary execution (macOS)
      if: matrix.os == 'macos-latest'
      working-directory: ./web-app-exe
      run: |
        # Test if binary exists
        if [ ! -f "${{ matrix.binary }}" ]; then
          echo "Binary not found"
          exit 1
        fi
        # Make binary executable
        chmod +x "${{ matrix.binary }}"
        # Test if binary is executable
        ./"${{ matrix.binary }}" --help
      shell: bash

    - name: Upload artifacts
      uses: actions/upload-artifact@v3
      with:
        name: binaries-${{ matrix.os }}
        path: |
          web-app-exe/find-place-web-app_*
        retention-days: 5