name: Binary Tests

on:
  push:
    paths:
      - 'web-app-exe/**'
    branches: [ main ]
  pull_request:
    paths:
      - 'web-app-exe/**'
    branches: [ main ]

jobs:
  test-binaries:
    name: Test Binaries
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [windows-latest, macos-latest]
        include:
          - os: windows-latest
            binary: find-place-web-app_windows_amd64.exe
          - os: macos-latest
            binary: find-place-web-app_darwin_amd64

    steps:
    - uses: actions/checkout@v4

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.21'

    - name: Install dependencies
      working-directory: ./web-app-exe
      run: go mod download

    - name: Setup Docker (Windows)
      if: matrix.os == 'windows-latest'
      shell: powershell
      run: |
        # Install Docker CLI
        $ProgressPreference = 'SilentlyContinue'
        Write-Host "Downloading Docker..."
        Invoke-WebRequest -UseBasicParsing -OutFile docker.exe https://download.docker.com/win/static/stable/x86_64/docker-24.0.7.zip
        Expand-Archive docker.exe -DestinationPath $Env:ProgramFiles\Docker
        Remove-Item -Force docker.exe
        $Env:Path = $Env:Path + ";$Env:ProgramFiles\Docker"
        
        # Install Docker Compose
        Write-Host "Installing Docker Compose..."
        $composeVersion = "v2.23.3"
        Invoke-WebRequest -UseBasicParsing -OutFile $Env:ProgramFiles\Docker\docker-compose.exe "https://github.com/docker/compose/releases/download/$composeVersion/docker-compose-windows-x86_64.exe"
        
        # Start Docker service
        Write-Host "Starting Docker service..."
        Start-Service docker
        
        # Wait for Docker to be ready
        Write-Host "Waiting for Docker to be ready..."
        $retries = 30
        $ready = $false
        while ($retries -gt 0 -and -not $ready) {
            try {
                docker version
                $ready = $true
            } catch {
                Write-Host "Waiting for Docker to be ready..."
                Start-Sleep -Seconds 10
                $retries--
            }
        }
        
        if (-not $ready) {
            Write-Error "Docker failed to start"
            exit 1
        }
        
        # Verify Docker Compose
        Write-Host "Verifying Docker Compose..."
        docker compose version

    - name: Setup Docker (macOS)
      if: matrix.os == 'macos-latest'
      run: |
        # Install Docker
        brew install docker docker-compose
        brew install --cask docker
        
        # Start Docker
        open -a Docker
        
        # Wait for Docker to start
        for i in {1..30}; do
          if docker info > /dev/null 2>&1; then
            echo "Docker is ready"
            break
          fi
          echo "Waiting for Docker to be ready..."
          sleep 10
        done
        
        # Verify Docker is running
        docker version
        docker compose version

    - name: Install Playwright Browser Dependencies (macOS)
      if: matrix.os == 'macos-latest'
      run: |
        brew install webkit2png
        brew install --cask chromium
        brew install --cask firefox

    - name: Install Playwright Browser Dependencies (Windows)
      if: matrix.os == 'windows-latest'
      run: |
        choco install chromium -y
        choco install firefox -y

    - name: Run Go tests
      working-directory: ./web-app-exe
      run: go test -v ./tests/...

    - name: Build binaries
      working-directory: ./web-app-exe
      run: |
        chmod +x build-exe.sh
        ./build-exe.sh
      shell: bash

    - name: Test binary execution (Windows)
      if: matrix.os == 'windows-latest'
      working-directory: ./web-app-exe
      run: |
        # Test if binary exists
        if (!(Test-Path "${{ matrix.binary }}")) {
          Write-Error "Binary not found"
          exit 1
        }
        # Test if binary is executable
        $env:PATH = "$env:PATH;C:\Program Files\Docker\Docker"
        $process = Start-Process -FilePath ".\${{ matrix.binary }}" -ArgumentList "--help" -NoNewWindow -PassThru -Wait
        if ($process.ExitCode -ne 0) {
          Write-Error "Binary execution failed"
          exit 1
        }

    - name: Test binary execution (macOS)
      if: matrix.os == 'macos-latest'
      working-directory: ./web-app-exe
      run: |
        # Test if binary exists
        if [ ! -f "${{ matrix.binary }}" ]; then
          echo "Binary not found"
          exit 1
        fi
        # Make binary executable
        chmod +x "${{ matrix.binary }}"
        # Test if binary is executable
        ./"${{ matrix.binary }}" --help
      shell: bash

    - name: Upload artifacts
      uses: actions/upload-artifact@v3
      with:
        name: binaries-${{ matrix.os }}
        path: |
          web-app-exe/find-place-web-app_*
        retention-days: 5