name: Create ZIP Archive

on:
  push:
    branches: [ "main" ]
  schedule:
    - cron: '0 0 */89 * *'  # Run every 89 days at midnight UTC


permissions:
  contents: write
  issues: write

jobs:
  create-zip-and-update-readme:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Upload files as artifact
      uses: actions/upload-artifact@v4
      with:
        name: find-place-hotel-web-app
        path: |
          ./docker-compose.yml
          ./requirements.txt
          ./get_auth_headers.py
          ./.env.example
        retention-days: 90
        overwrite: true
        include-hidden-files: true

    - name: Get Artifact Download URL and Update README
      env:
        GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        # Get the most recent workflow run ID
        WORKFLOW_RUN_ID=$(gh run list --workflow="Create ZIP Archive" --limit 1 --json databaseId --jq '.[0].databaseId')
        
        # Get artifact ID
        ARTIFACT_ID=$(gh api "/repos/${{ github.repository }}/actions/runs/${WORKFLOW_RUN_ID}/artifacts" --jq '.artifacts[0].id')
        
        # Construct the correct download URL
        ARTIFACT_URL="https://github.com/${{ github.repository }}/actions/runs/${WORKFLOW_RUN_ID}/artifacts/${ARTIFACT_ID}"
        
        # Update the "Download the zip file" link with the specific pattern
        sed -i 's|Download the zip file: \[Web App ZIP\](https://github.com/sakan811/Find-the-Best-Place-to-Stay-with-Price-per-Review/actions/runs/.*/artifacts/.*)|Download the zip file: [Web App ZIP]('"$ARTIFACT_URL"')|g' README.md

    - name: Create a new branch
      run: |
        git checkout -b update-readme-${{ github.run_number }}

    - name: Commit README changes
      run: |
        git config --global user.name 'GitHub Actions Bot'
        git config --global user.email 'actions@github.com'
        git add README.md
        git commit -m "Update web app ZIP download link" || exit 0

    - name: Push changes
      run: |
        git push origin update-readme-${{ github.run_number }}

    - name: Create Issue
      env:
        GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        gh issue create --title "README Update: New ZIP link available" \
                        --body "A new branch 'update-readme-${{ github.run_number }}' has been created with updates to the README.md file. Please review and create a pull request if the changes are acceptable."
