name: Create ZIP Archive
on:
  push:
    branches: [ "main" ]
  schedule:
    - cron: '0 0 */89 * *'  # Run every 89 days at midnight UTC
permissions:
  contents: write
  issues: write
jobs:
  create-zip-and-update-readme:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
    - name: Upload files as artifact
      uses: actions/upload-artifact@v4
      with:
        name: find-place-hotel-web-app
        path: |
          ./docker-compose.yml
          ./requirements.txt
          ./get_auth_headers.py
          ./.env.example
        retention-days: 90
        overwrite: true
        include-hidden-files: true
    - name: Get Artifact Download URL
      env:
        GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        # Get the most recent workflow run ID
        WORKFLOW_RUN_ID=$(gh run list --workflow="Create ZIP Archive" --limit 1 --json databaseId --jq '.[0].databaseId')
        
        # Get artifact ID
        ARTIFACT_ID=$(gh api "/repos/${{ github.repository }}/actions/runs/${WORKFLOW_RUN_ID}/artifacts" --jq '.artifacts[0].id')
        
        # Construct the correct download URL
        ARTIFACT_URL="https://github.com/${{ github.repository }}/actions/runs/${WORKFLOW_RUN_ID}/artifacts/${ARTIFACT_ID}"
        
        # Create an issue with just the artifact URL
        gh issue create --title "New Web App ZIP Artifact Available" \
                        --body "Artifact Download URL: $ARTIFACT_URL Please update the README.md with this link manually."
