name: Docker CI

on:
  pull_request:
    branches: [ "main" ]
  push:
    branches: [ "main" ]

permissions:
  contents: read
  security-events: write
  pull-requests: write
  issues: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ vars.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      
      - name: Build backend
        id: build-backend
        uses: docker/build-push-action@v6
        with:
          context: ./backend
          push: ${{ github.event_name != 'pull_request' }}
          load: ${{ github.event_name == 'pull_request' }}
          tags: ${{ vars.DOCKERHUB_USERNAME }}/find-stay-place-backend:latest

      - name: Build frontend
        id: build-frontend
        uses: docker/build-push-action@v6
        with:
          context: ./frontend
          push: ${{ github.event_name != 'pull_request' }}
          load: ${{ github.event_name == 'pull_request' }}
          tags: ${{ vars.DOCKERHUB_USERNAME }}/find-stay-place-frontend:latest
      
      - name: Build auth-headers
        id: build-auth-headers
        uses: docker/build-push-action@v6
        with:
          context: ./auth_headers
          push: ${{ github.event_name != 'pull_request' }}
          load: ${{ github.event_name == 'pull_request' }}
          tags: ${{ vars.DOCKERHUB_USERNAME }}/find-stay-place-auth-headers:latest

      - name: Docker Scout for backend
        if: ${{ github.event_name == 'pull_request' }}
        uses: docker/scout-action@v1
        with:
          command: cves,recommendations,compare
          image: ${{ vars.DOCKERHUB_USERNAME }}/find-stay-place-backend:latest
          ignore-unchanged: true
          only-severities: critical,high
          github-token: ${{ secrets.GITHUB_TOKEN }}
          
      - name: Docker Scout for frontend
        if: ${{ github.event_name == 'pull_request' }}
        uses: docker/scout-action@v1
        with:
          command: cves
          image: ${{ vars.DOCKERHUB_USERNAME }}/find-stay-place-frontend:latest
          ignore-unchanged: true
          only-severities: critical,high
          github-token: ${{ secrets.GITHUB_TOKEN }}
          organization: ${{ vars.DOCKERHUB_USERNAME }}
          
      - name: Docker Scout for auth-headers
        if: ${{ github.event_name == 'pull_request' }}
        uses: docker/scout-action@v1
        with:
          command: cves
          image: ${{ vars.DOCKERHUB_USERNAME }}/find-stay-place-auth-headers:latest
          ignore-unchanged: true
          only-severities: critical,high
          github-token: ${{ secrets.GITHUB_TOKEN }}
