name: Docker Build

on:
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read
  security-events: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Build backend
        uses: docker/build-push-action@v6
        with:
          context: ./backend
          push: false
          tags: ${{ vars.DOCKERHUB_USERNAME }}/find-stay-place-backend:latest

      - name: Build frontend
        uses: docker/build-push-action@v6
        with:
          context: ./frontend
          push: false
          tags: ${{ vars.DOCKERHUB_USERNAME }}/find-stay-place-frontend:latest
      
      - name: Build auth-headers
        uses: docker/build-push-action@v6
        with:
          context: ./auth_headers
          push: false
          tags: ${{ vars.DOCKERHUB_USERNAME }}/find-stay-place-auth-headers:latest
