name: Test EXE File

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test-windows:
    runs-on: windows-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Run EXE file tests on Windows
        run: |
          .\app-windows.exe --test
        shell: cmd

  test-macos:
    runs-on: macos-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Run EXE file tests on macOS
        run: |
          chmod +x ./app-mac
          ./app-mac --test

  test-linux:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Run EXE file tests on Linux
        run: |
          chmod +x ./app-linux
          ./app-linux --test
