name: Test EXE File

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Run EXE file test
        run: |
          ${{ matrix.os == 'windows-latest' && '.\app-windows.exe' || './app-' }}${{ matrix.os == 'macos-latest' && 'mac' || 'linux' }} --test | tee output.log

      - name: Check for specific error
        if: failure()
        run: |
          ${{ matrix.os == 'windows-latest' && 'findstr' || 'grep' }} "Press 'Enter' to exit..." output.log && echo "::warning::Docker may not be running or there was an issue with docker-compose" || echo "::error::Unexpected error occurred"

      - name: Verify service is up
        run: |
          timeout 60 bash -c 'while [[ "$(curl -s -o /dev/null -w ''%{http_code}'' localhost:5000)" != "200" ]]; do sleep 5; done' || exit 1

      - name: Clean up
        if: always()
        run: docker-compose down