name: Frontend Test

on:
  push:
    paths:
      - 'frontend/**'
      - '.github/workflows/frontend-test.yml'
      - 'package.json'
      - 'package-lock.json'
    branches:
      - main
  pull_request:
    paths:
      - 'frontend/**'
      - '.github/workflows/frontend-test.yml'
      - 'package.json'
      - 'package-lock.json'
    branches:
      - main

jobs:
  test:
    strategy:
      matrix:
        node-version:
          - 20

    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'
          cache-dependency-path: './frontend/package-lock.json'

      - name: Install dependencies
        working-directory: ./frontend
        run: npm install

      - name: Run ESLint
        working-directory: ./frontend
        run: npx eslint .

      - name: Run tests
        working-directory: ./frontend
        run: npm test

