name: Go Tests

on:
  push:
    paths:
      - 'web-app-exe/**'
      - '.github/workflows/go-test.yml'
      - 'go.mod'
      - 'go.sum'
    branches: [ main ]
  pull_request:
    paths:
      - 'web-app-exe/**'
      - '.github/workflows/go-test.yml'
      - 'go.mod'
      - 'go.sum'
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.21'

    - name: Run Tests
      working-directory: ./web-app-exe
      run: go test -v ./... 