name: Go Tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  check_changes:
    runs-on: ubuntu-latest
    outputs:
      should_run: ${{ steps.filter.outputs.go_code }}
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: dorny/paths-filter@v2
        id: filter
        with:
          filters: |
            go_code:
              - 'web-app-exe/**'
              - '.github/workflows/go-test.yml'
              - 'go.mod'
              - 'go.sum'

  test:
    needs: check_changes
    if: ${{ needs.check_changes.outputs.should_run == 'true' }}
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.21'

    - name: Run Tests
      working-directory: ./web-app-exe
      run: go test -v ./... 