name: Lint

on: # yamllint disable-line rule:truthy
  push: null
  pull_request: null

permissions:
  contents: read

jobs:
  lint:
    name: Check Code
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: read
      statuses: write
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      
      - name: Super-Linter
        uses: super-linter/super-linter@v7.2.1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  fix-lint-issues:
    name: Fix Issues
    needs: lint
    if: failure() && github.event_name == 'pull_request'
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
      statuses: write
    
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
          ref: ${{ github.head_ref }}
      
      - name: Super-Linter Fix
        uses: super-linter/super-linter@v7.2.1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          # Enable auto-fixing
          FIX_PYTHON_BLACK: true
          FIX_PYTHON_ISORT: true
          FIX_PYTHON_RUFF: true
          FIX_TYPESCRIPT_ES: true
          FIX_JAVASCRIPT_ES: true
          FIX_ENV: true
          FIX_GO: true
          FIX_TSX: true
          FIX_YAML_PRETTIER: true
          FIX_MARKDOWN_PRETTIER: true
          FIX_SHELL_SHFMT: true

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v6
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          commit-message: "style: auto-fix linting issues"
          title: "style: fix linting issues"
          body: |
            Auto-generated PR to fix linting issues.
            
            Changes made by Super-Linter auto-fix.
          branch: fix/linting-issues
          base: ${{ github.head_ref || github.ref_name }}
          labels: |
            automated pr
            linting