name: Trivy Docker Scan

on:
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Build backend
        uses: docker/build-push-action@v6
        with:
          context: ./backend
          push: false
          tags: ${{ vars.DOCKERHUB_USERNAME }}/find-stay-place-backend:latest

      - name: Build frontend
        uses: docker/build-push-action@v6
        with:
          context: ./frontend
          push: false
          tags: ${{ vars.DOCKERHUB_USERNAME }}/find-stay-place-frontend:latest

      - name: Run Trivy vulnerability scanner for Backend
        uses: aquasecurity/trivy-action@master
        with:
          image-ref: '${{ vars.DOCKERHUB_USERNAME }}/find-stay-place-backend:latest'
          format: 'table'

      - name: Run Trivy vulnerability scanner for Frontend
        uses: aquasecurity/trivy-action@master
        with:
          image-ref: '${{ vars.DOCKERHUB_USERNAME }}/find-stay-place-frontend:latest'
          format: 'table'